Display information from openweather API.
igakigongo/js-weather-app pull request #1
Opened 2020-02-10 18:52 UTC by igakigongo

… ui updates

2020-02-13 07:52 UTC, Oghenebrume50 requested changes
### STATUS: CHANGES REQUIRED 

Hi @igakigongo  good job on this project the code seems nice enough, however, I couldn't test it, nothing shows up when I click on the find button, but I outlined some changes for you anyways, :slightly_smiling_face: please look into those and see why nothing shows up for me too

- it seems the eslint file was modified, ![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) 
[see correct eslint file](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json)

**please request for another review when you are done** :slightly_smiling_face: 

**RAPHAEL NORIODE** :sunglasses:

2020-02-13 07:52 UTC, Oghenebrume50 commented on src/js/app.js
> +Node.prototype.clearAfter = function (seconds) {
For this eslint rule above wouldn't adding a name after the function keyword solve the problem :thinking: I believe it would

2020-02-13 07:52 UTC, Oghenebrume50 commented on src/js/api-client.js
> +export const convertTemperature = (tempInKelvin, tempFormat) => {
There is suppose to be a request made for both Celsius and Fahrenheit data you aren't supposed to get one and calculate the other ![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/requests_requirement.png)

2020-02-14 19:41 UTC, igakigongo commented
**For a live demo please visit this [URL](https://objective-lewin-2369a5.netlify.com)**

2020-02-14 21:22 UTC, Oghenebrume50 requested changes
### STATUS: CHANGES REQUIRED 

Hi @igakigongo good job on making changes, please fix the suggestion and request for another review, it is super important. 

**RAPHAEL NORIODE** :sunglasses:

2020-02-14 21:22 UTC, Oghenebrume50 commented on src/js/api-client.js
> +// };
It’s better to delete commented code. If you need to review a previous version of your code, use git history 
![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png)

2020-02-14 22:33 UTC, Oghenebrume50 approved these changes
### STATUS: APPROVED 

Hi @igakigongo this looks good, **This is approved**, please merge and move on 

**RAPHAEL NORIODE** :sunglasses:

2020-02-14 22:41 UTC, merged